language: python
matrix:
  include:
  - python: 3.6
    dist: xenial
    sudo: true
    env: TOXENV=lint,unittest
  - python: 3.7
    dist: xenial
    sudo: true
    env: TOXENV=lint,unittest

install:
  - pip install tox
script:
  - tox
deploy:
  provider: pypi
  user: freelancer
  password:
    secure: jd+MR8uMI+jbMFFr1ERxn7jUjoxBYySD8gW9UKrUaSNARb8r98GlAnuE/CauRI5N33CJgJugvpIIlJXkmkhI0FES476qmepiTP6d+RbpcYK/K6t3zpFASKRy82Fe6LWSQZFM4qkVxQI9INExPv5bNHy6NdYh4/4qfT0YZcDgiPvsSRytSdmqwfc4G1UBpJA1ZLLpLh9LIpDDDmu9Yf2u1Vw41mEWtIZmC8vkEMHA7D8sqjPf/V+w4S4dUNhHhd4gkFC/JK8qXUzbXl9qaY3R3Xd6BfEGqlIPkwFXidZhVQrbP8RPdOT3GDlDBn35t2Y0gqzspBPMIBfoaCdwTIqA8N2s/H651cQXDMK3FB+XDCpLGKWwWGFOmZ9tEldmDqHSHPpNcyCelWshBTOFT+BxJW91ceI0t7pC3YmikCrYZPKA6dLFvYEi+1WsTEvKuW1tvMwpax5E6go1rtjUzhtQwLkeH4u5fLuTzw/O039jtlSY1ur75RsdqzVdgCpUTagsAbq7zLxkQsk+old8ovpz9FurJaDLsSFTwVcGTClpx2rreZf4+4+6j3DD5Tjmm030kh0A5DdgN/d9SqPZLDfwRhrLcm8Ny03Sz+WwmkiknlIWHfNjCVMm68baQkxBBT84XmX1B7z1w2bYI45GLXHN3RzJWP8vH7L/EHP+Vxh7u5s=
  on:
    tags: true
  distributions: sdist bdist_wheel
